// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1hPfbQeCot6lvnlyHIvipa5O407bDAc',
    appId: '1:315602019032:web:2eb405363c0c730ad76dad',
    messagingSenderId: '315602019032',
    projectId: 'pet4life-2023-2024',
    authDomain: 'pet4life-2023-2024.firebaseapp.com',
    storageBucket: 'pet4life-2023-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ktQBcthyqAPUqvtWA_4hC_-8cle9qQA',
    appId: '1:315602019032:android:fa21e7c5841adcd2d76dad',
    messagingSenderId: '315602019032',
    projectId: 'pet4life-2023-2024',
    storageBucket: 'pet4life-2023-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXBZVz9gdHlSTCuAFg4_q7KldIPX-3Yk',
    appId: '1:315602019032:ios:bfb7a465e70daab2d76dad',
    messagingSenderId: '315602019032',
    projectId: 'pet4life-2023-2024',
    storageBucket: 'pet4life-2023-2024.appspot.com',
    androidClientId: '315602019032-ic9f2fvtnr015pa9j52kk08c0269o5lv.apps.googleusercontent.com',
    iosClientId: '315602019032-off5t000t62k4vgllq7940bsi3cobera.apps.googleusercontent.com',
    iosBundleId: 'be.hepl.pet4life',
  );
}
